language: python
branches:
  only:
  - master
install:
- pip install pelican ghp-import markdown lesscpy
script:
- make travis
env:
  global:
    secure: "VGAummqCVQQCLSmoSpn9p2kSAA8dMksWDxlufe0kc90iOxaEsavkdawDgDyYvHwxWOwpyVcn2qIDwgssUzB0wiG2b7b11GweKkEgLU4tAoTfiTlZEgwxeYCmRA9EltG/g7puP8AowKLMbeFJCIZx9J/L/OrujUVEgiqU2+mge/0="