language: python
branches:
  only:
  - master
before_install:
- wget http://mirrors.kernel.org/ubuntu/pool/universe/f/fonts-crosextra-carlito/fonts-crosextra-carlito_20130920-1_all.deb http://mirrors.kernel.org/ubuntu/pool/universe/f/fonts-crosextra-caladea/fonts-crosextra-caladea_20130214-1_all.deb
- sudo dpkg -i fonts-crosextra-carlito_20130920-1_all.deb fonts-crosextra-caladea_20130214-1_all.deb
- sudo add-apt-repository ppa:texlive-backports/ppa -y
- sudo apt-get update
- sudo apt-get install -y texlive-xetex texlive-latex-extra msttcorefonts
install:
- pip install pelican ghp-import markdown lesscpy
script:
- make travis
env:
  global:
    secure: "VGAummqCVQQCLSmoSpn9p2kSAA8dMksWDxlufe0kc90iOxaEsavkdawDgDyYvHwxWOwpyVcn2qIDwgssUzB0wiG2b7b11GweKkEgLU4tAoTfiTlZEgwxeYCmRA9EltG/g7puP8AowKLMbeFJCIZx9J/L/OrujUVEgiqU2+mge/0="
