language: python
branches:
  only:
  - master
install:
- pip install pelican ghp-import markdown
script:
- make travis
env:
  global:
    secure: "H5TLt43YN1o9wyg3N78oOCaowTPyZ30e7tELPwx4/+BTT0lAJFe1a2ZcG67JoGXU3Wdg5qolfn6ojq95RUtQIRFAy1AcwU+uRWmOB9F5CdsAo0dLuj0InO+Ns+YldEPqCYmXK7zxw7aLHralrBTOrwBOB6Ji8BVqV2OPK5rKxkQ="
